#!/usr/bin/env node
// Builds assets/rotation-data.js — the curated dish rotation that powers the
// homepage hero + waitlist showcase + the "India's food" gallery.
//
// Sources (NEVER hand-edit the numbers — core rule: macros are NIN-computed):
//   - ../food-database/dishes_mvp.csv            native names (native-speaker verified)
//   - ../food-database/layer3-dishes/dish_macros.csv  per-serving macros (generated)
//   - Supabase catalog.dishes.image_url          dish photos (public read)
//
// Run from svas-site/:  node scripts/build_rotation.js
// Re-run whenever a curated dish's recipe/macros change, then commit the output.

const fs = require("fs");
const path = require("path");

const SUPABASE_URL = "https://jtschfacrjsynryiyyyk.supabase.co";
const KEY = "sb_publishable_2uL2zVf_cpObToPtKODMZw_cH0c8TIe"; // publishable — safe

// Curated picks — the most homely, recognizable dish per state.
// HERO: 8 states, all 8 native scripts distinct (Telugu, Tamil, Malayalam,
// Kannada, Gurmukhi, Gujarati, Bengali, Devanagari).
const HERO = [
  ["tel_pesarattu", "Andhra Pradesh"],
  ["pun_rajma_chawal", "Punjab"],
  ["kl_puttu", "Kerala"],
  ["gj_dhokla", "Gujarat"],
  ["tn_ven_pongal", "Tamil Nadu"],
  ["bn_macher_jhol", "West Bengal"],
  ["kn_bisi_bele_bath", "Karnataka"],
  ["mh_kanda_poha", "Maharashtra"],
];
// GALLERY: 8 more states → 16 dishes / 16 states in the showcase strip.
const GALLERY_EXTRA = [
  ["tel_sarva_pindi", "Telangana"],
  ["as_masor_tenga", "Assam"],
  ["od_dalma", "Odisha"],
  ["bh_litti_chokha", "Bihar"],
  ["rj_dal_baati_churma", "Rajasthan"],
  ["hp_chana_madra", "Himachal Pradesh"],
  ["ga_fish_curry", "Goa"],
  ["sk_thukpa", "Sikkim"],
];

// minimal CSV parser (quoted fields, LF lines)
function parseCsv(text) {
  const rows = [];
  let row = [], field = "", inQ = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQ) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false;
      } else field += ch;
    } else if (ch === '"') inQ = true;
    else if (ch === ",") { row.push(field); field = ""; }
    else if (ch === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else if (ch !== "\r") field += ch;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function loadCsvById(file, idCol) {
  const rows = parseCsv(fs.readFileSync(file, "utf8"));
  const header = rows[0];
  const map = {};
  for (const r of rows.slice(1)) {
    if (!r[0]) continue;
    const rec = {};
    header.forEach((h, i) => (rec[h] = r[i]));
    map[rec[idCol]] = rec;
  }
  return map;
}

async function main() {
  const root = path.join(__dirname, "..", "..");
  const dishes = loadCsvById(path.join(root, "food-database", "dishes_mvp.csv"), "dish_id");
  const macros = loadCsvById(path.join(root, "food-database", "layer3-dishes", "dish_macros.csv"), "dish_id");

  const ids = [...HERO, ...GALLERY_EXTRA].map(([id]) => id);
  const res = await fetch(
    `${SUPABASE_URL}/rest/v1/dishes?select=dish_id,image_url&dish_id=in.(${ids.join(",")})`,
    { headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, "Accept-Profile": "catalog" } }
  );
  if (!res.ok) throw new Error(`Supabase ${res.status}`);
  const imgs = Object.fromEntries((await res.json()).map((r) => [r.dish_id, r.image_url]));

  function build([id, state]) {
    const d = dishes[id], m = macros[id], img = imgs[id];
    if (!d) throw new Error(`${id}: not in dishes_mvp.csv`);
    if (!m) throw new Error(`${id}: not in dish_macros.csv`);
    if (!img) throw new Error(`${id}: no image_url in Supabase`);
    if (!d.native_name) throw new Error(`${id}: blank native name — pick another dish`);
    return {
      id,
      state,
      name: d.display_name,
      native: d.native_name,
      kcal: Math.round(+m.kcal),
      p: Math.round(+m.protein_g),
      f: Math.round(+m.fat_g),
      c: Math.round(+m.carb_g),
      img, // raw object URL — hero.js rewrites to the edge-cached render endpoint
    };
  }

  const hero = HERO.map(build);
  const gallery = [...HERO, ...GALLERY_EXTRA].map(build);

  const out =
    "// GENERATED by scripts/build_rotation.js — do not hand-edit.\n" +
    "// Macros are per serving, NIN-computed (IFCT-2017). Native names native-speaker verified.\n" +
    "window.SVAS_ROTATION = " + JSON.stringify({ hero, gallery }, null, 1) + ";\n";
  fs.writeFileSync(path.join(__dirname, "..", "assets", "rotation-data.js"), out);
  console.log(`rotation-data.js: ${hero.length} hero + ${gallery.length} gallery dishes`);
  for (const d of hero) console.log(`  ${d.state}: ${d.name} (${d.native}) ${d.kcal} kcal / ${d.p}g P`);
}

main().catch((e) => { console.error(e); process.exit(1); });
